# Generated by Django 5.0.6 on 2024-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
