# Generated by Django 5.0.6 on 2024-05-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_slug_alter_book_count_alter_book_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBookCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Book_carousel')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.category'),
        ),
    ]
