# Generated by Django 5.0.6 on 2024-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homebookcarousel_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
