# Generated by Django 5.0.6 on 2024-05-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued',
            field=models.IntegerField(default=0),
        ),
    ]
