# Generated by Django 5.0.6 on 2024-07-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='book',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookrequest'),
        ),
    ]
